language: julia
julia:
  - 0.7.0
  - 1.0.0
  - 1.6.0
  - 1.9.0
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
after_success:
  - julia -e 'cd(Pkg.dir("AdaptiveRejectionSampling")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
